Move alert banner to the top
trilitech/tezos-staking-app pull request #70
Opened 2024-07-10 13:39 UTC by ajinkyaraj-23

- **shuffle bakers list (#63)**
- **replace delegate button with centered select baker button**
- **get rid of maxW**
- **add baker info expand table**
- **move alert icon to the top**

2024-07-10 13:44 UTC, rickykuo666 submitted a review, later dismissed
LGTM

2024-07-12 15:24 UTC, rickykuo666 requested changes

2024-07-12 15:24 UTC, rickykuo666 commented on components/icons/WarningIcon.tsx
> +  color,
and add this `   {...styles}` to Icon

2024-07-12 15:24 UTC, rickykuo666 commented on components/DisabledStakeAlert.tsx
so can remove `StakingAlertBox` and its just like this 

```
export const DisabledStakeAlert = ({
  opStatus,
  acctInfo,
  ...styles
}: {
  opStatus: StakingOpsStatus
  acctInfo: AccountInfo | null
} & BoxProps) => {
  let backgroundColor = 'gray.200'

  if (opStatus.Delegated && !opStatus.CanStake) {
    if (!opStatus.bakerAcceptsStaking && (acctInfo?.stakedBalance ?? 0) > 0) {
      backgroundColor = 'red.200'
    }
    return (
      <Box w='100%' borderLeft='4px solid gray' p={4} {...styles}>
        <Flex alignItems='center' gap='12px'>
          <WarningIcon fill={backgroundColor} />
          <Text fontSize='16px' lineHeight='22px' color='#2D3748'>
            {getDisabledStakeButtonReason(opStatus)}
          </Text>
        </Flex>
      </Box>
    )
  }
}

```

2024-07-12 16:34 UTC, ajinkyaraj-23 commented on components/icons/WarningIcon.tsx
> +  color,
Done

2024-07-12 16:34 UTC, ajinkyaraj-23 commented on components/DisabledStakeAlert.tsx
Done.

2024-07-15 09:58 UTC, merged